[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
black = "*"
codeforlife-portal = "*"
django-import-export = "==3.3.1"
django-test-migrations = "==1.2.0"
pytest = "*"
pytest-cov = "*"
pytest-django = "==4.5.2"
pytest-pythonpath = "*"

[packages]
aimmo = {editable = true, path = "."}
django-formtools = "==2.2"
django-otp = "==1.0.2"
docker = "<6"
eventlet = "*"
importlib-metadata = "<5" # Using version 5 causes an issue when trying to run pytest. Not sure why, linked to: https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
kubernetes = "==26.1.0"
pyyaml = "==5.4.1"
setuptools = "==62.1.0"
wheel = "*"

[requires]
python_version = "3.8"

[pipenv]
allow_prereleases = true
