[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pytest = "~=6.2"
pytest-django = "==4.5.2"
pytest-pythonpath = "*"
codeforlife-portal = "*"
pytest-cov = "*"
black = "*"
django-test-migrations = "==1.2.0"
django-import-export = "*"

[packages]
aimmo = {editable = true, path = "."}
kubernetes = "==26.1.0"
eventlet = "*"
docker = "<6"
wheel = "*"
importlib-metadata = "<5" # Using version 5 causes an issue when trying to run pytest. Not sure why, linked to: https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
